#!/bin/sh
# postinst script for multiflexi-mserver
set -e

case "$1" in
    configure)
        multiflexi-cli credential-prototype:import-json --file=/usr/lib/multiflexi-mserver/multiflexi/mserver.credprototype.json
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
