#!/bin/sh

set -e

file /usr/lib/multiflexi-mserver/multiflexi/mserver.credprototype.json
cat /usr/lib/multiflexi-mserver/multiflexi/mserver.credprototype.json


multiflexi-cli crprototype import-json --file=/usr/lib/multiflexi-mserver/multiflexi/mserver.credprototype.json

#DEBHELPER#

exit 0
